# Generated by Django 6.0.7 on 2026-07-09 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Living Room', 'Living Room'), ('Bedroom', 'Bedroom'), ('Dining Room', 'Dining Room'), ('Chairs', 'Chairs')], default='Living Room', max_length=50),
        ),
    ]
